.include "patches/asset/gfx/ts/ts.asm"
.include "patches/asset/gfx/trainerbattle_backsprites/trainerbattle_backsprites.asm"
.include "patches/asset/gfx/badges/badges.asm"
.include "patches/asset/gfx/intro/intro.asm"
.include "patches/asset/gfx/bootscreen/bootscreen.asm"