.include "patches/spielbeginn/spielbeginn.asm"
.include "patches/asset/asset.asm"
.include "patches/ts_cry/ts_cry.asm"
.include "patches/overworld/ow_pal_table.asm"
.include "patches/overworld/ow_table.asm"