.include "patches/spielbeginn/spielbeginn.asm"
.include "patches/asset/asset.asm"
.include "patches/ts_cry/ts_cry.asm"
.include "patches/overworld/ow_pal_table.asm"
.include "patches/overworld/ow_table.asm"
.include "patches/help_menu/remove_help_menu.asm"
.include "patches/start_menu.asm"
.include "patches/save/save.asm"