@ File generated by m4a2s Wave-Module
	.section .rodata
	.global	wave_041
	.align	2

wave_041:

	.hword	0x0000, 0x0000
	.word	0xFA0000 @ Mid-C pitch ~16000 Hz
	.word	0 @ Loop Start
	.word	1 @ Loop End

	.byte	0x00

	.end
