@ File generated by m4a2s Wave-Module
	.section .rodata
	.global	wave_040
	.align	2

wave_040:

	.hword	0x0000, 0x0000
	.word	0x0 @ Mid-C pitch ~0 Hz
	.word	0 @ Loop Start
	.word	0 @ Loop End


	.end
