// DarkGengar
// License GPL for more details see License.txt
// Generated by Pointer Finder

// Pokemon name table
.org 0x8000144
	.word str_poke_name_list

.org 0x80113d4
	.word str_poke_name_list

.org 0x8011490
	.word str_poke_name_list

.org 0x8011528
	.word str_poke_name_list

.org 0x8011640
	.word str_poke_name_list

.org 0x8034c80
	.word str_poke_name_list

.org 0x8040eec
	.word str_poke_name_list

.org 0x80434dc
	.word str_poke_name_list

.org 0x8049788
	.word str_poke_name_list

.org 0x8053afc
	.word str_poke_name_list

.org 0x8053b64
	.word str_poke_name_list

.org 0x806bc84
	.word str_poke_name_list

.org 0x806bcd0
	.word str_poke_name_list

.org 0x8093fa4
	.word str_poke_name_list

.org 0x809f64c
	.word str_poke_name_list

.org 0x80a09ec
	.word str_poke_name_list

.org 0x80bd90c
	.word str_poke_name_list

.org 0x80cb2d8
	.word str_poke_name_list

.org 0x80cc064
	.word str_poke_name_list

.org 0x80ce254
	.word str_poke_name_list

.org 0x80ce858
	.word str_poke_name_list

.org 0x80cea70
	.word str_poke_name_list

.org 0x80e6740
	.word str_poke_name_list

.org 0x80f35ac
	.word str_poke_name_list

.org 0x8103814
	.word str_poke_name_list

.org 0x81038ec
	.word str_poke_name_list

.org 0x810398c
	.word str_poke_name_list

.org 0x8103a24
	.word str_poke_name_list

.org 0x8103ac0
	.word str_poke_name_list

.org 0x8103b20
	.word str_poke_name_list

.org 0x810511c
	.word str_poke_name_list

.org 0x810605c
	.word str_poke_name_list

.org 0x810672c
	.word str_poke_name_list

.org 0x8113fc0
	.word str_poke_name_list

.org 0x8119530
	.word str_poke_name_list

.org 0x811ad78
	.word str_poke_name_list

.org 0x811b0cc
	.word str_poke_name_list

.org 0x811b120
	.word str_poke_name_list

.org 0x8121944
	.word str_poke_name_list

.org 0x81363b4
	.word str_poke_name_list
