@ File generated by m4a2s Songtable-Module
	.section .rodata
.global	_songtable
	.align	2

_songtable:

@**************** Song 0000 ****************@

	.word	seq_000
	.byte	0x00, 0x00, 0x00, 0x00

	.end
