@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	bank_023
	.align	2

bank_023:

@**************** Voice 000 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_145
	.byte	255, 240, 255, 220

@**************** Voice 001 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_146
	.byte	255, 240, 255, 220

@**************** Voice 002 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_147
	.byte	255, 240, 180, 220

@**************** Voice 003 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_148
	.byte	255, 240, 180, 220



	.end
