@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	bank_003
	.align	2

bank_003:

@**************** Voice 000 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_052
	.byte	255, 247, 0, 188

@**************** Voice 001 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_053
	.byte	255, 247, 0, 188



	.end
