@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	bank_002
	.align	2

bank_002:

@**************** Voice 000 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_050
	.byte	255, 252, 0, 239

@**************** Voice 001 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_051
	.byte	255, 252, 0, 239



	.end
