@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	bank_025
	.align	2

bank_025:

@**************** Voice 000 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_157
	.byte	255, 245, 180, 196

@**************** Voice 001 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_158
	.byte	255, 245, 180, 196

@**************** Voice 002 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_159
	.byte	255, 245, 180, 196



	.end
