@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	bank_001
	.align	2

bank_001:

@**************** Voice 000 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_042
	.byte	255, 245, 0, 210

@**************** Voice 001 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_043
	.byte	255, 245, 0, 210

@**************** Voice 002 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_044
	.byte	255, 245, 0, 210

@**************** Voice 003 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_045
	.byte	255, 245, 0, 210

@**************** Voice 004 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_046
	.byte	255, 245, 0, 210

@**************** Voice 005 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_047
	.byte	255, 245, 0, 210

@**************** Voice 006 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_048
	.byte	255, 245, 0, 210

@**************** Voice 007 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_049
	.byte	255, 245, 0, 210



	.end
