@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	voicegroup001
	.align	2

voicegroup001:

@**************** Voice 000 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_000
	.byte	255, 0, 255, 24

@**************** Voice 001 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 002 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_001
	.word	map_000

@**************** Voice 003 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_002
	.word	map_001

@**************** Voice 004 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_003
	.word	map_002

@**************** Voice 005 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_004
	.word	map_003

@**************** Voice 006 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_001
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 007 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_005
	.word	map_004

@**************** Voice 008 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 009 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_062
	.byte	255, 220, 51, 242

@**************** Voice 010 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 011 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_006
	.word	map_005

@**************** Voice 012 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_007
	.word	map_006

@**************** Voice 013 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_008
	.word	map_007

@**************** Voice 014 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_009
	.word	map_008

@**************** Voice 015 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_010
	.word	map_009

@**************** Voice 016 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_002
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 017 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_011
	.word	map_010

@**************** Voice 018 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_012
	.word	map_011

@**************** Voice 019 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_093
	.byte	255, 0, 255, 159

@**************** Voice 020 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_094
	.byte	255, 0, 255, 200

@**************** Voice 021 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_013
	.word	map_012

@**************** Voice 022 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_099
	.byte	96, 240, 180, 165

@**************** Voice 023 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_100
	.byte	255, 0, 255, 0

@**************** Voice 024 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_014
	.word	map_013

@**************** Voice 025 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_105
	.byte	255, 252, 0, 239

@**************** Voice 026 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_106
	.byte	255, 0, 255, 195

@**************** Voice 027 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_015
	.word	map_014

@**************** Voice 028 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_110
	.byte	252, 0, 255, 240

@**************** Voice 029 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_016
	.word	map_015

@**************** Voice 030 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_017
	.word	map_016

@**************** Voice 031 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 032 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_018
	.word	map_017

@**************** Voice 033 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_122
	.byte	255, 253, 0, 149

@**************** Voice 034 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_123
	.byte	255, 245, 0, 149

@**************** Voice 035 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_124
	.byte	255, 0, 255, 188

@**************** Voice 036 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_125
	.byte	255, 235, 128, 99

@**************** Voice 037 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_126
	.byte	255, 0, 255, 165

@**************** Voice 038 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_127
	.byte	255, 0, 255, 165

@**************** Voice 039 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_128
	.byte	255, 254, 0, 200

@**************** Voice 040 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_019
	.word	map_018

@**************** Voice 041 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_133
	.byte	96, 0, 255, 127

@**************** Voice 042 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_134
	.byte	255, 210, 127, 127

@**************** Voice 043 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_135
	.byte	252, 0, 255, 240

@**************** Voice 044 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_136
	.byte	252, 0, 255, 240

@**************** Voice 045 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_020
	.word	map_019

@**************** Voice 046 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_021
	.word	map_020

@**************** Voice 047 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_022
	.word	map_021

@**************** Voice 048 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_023
	.word	map_022

@**************** Voice 049 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_149
	.byte	255, 0, 255, 165

@**************** Voice 050 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_150
	.byte	70, 0, 255, 127

@**************** Voice 051 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_024
	.word	map_023

@**************** Voice 052 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_153
	.byte	255, 250, 127, 165

@**************** Voice 053 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_154
	.byte	255, 0, 255, 127

@**************** Voice 054 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_155
	.byte	255, 0, 255, 0

@**************** Voice 055 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_156
	.byte	255, 248, 0, 165

@**************** Voice 056 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_025
	.word	map_024

@**************** Voice 057 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_026
	.word	map_025

@**************** Voice 058 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_027
	.word	map_026

@**************** Voice 059 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_025
	.word	map_024

@**************** Voice 060 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_028
	.word	map_027

@**************** Voice 061 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_029
	.word	map_028

@**************** Voice 062 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_030
	.word	map_024

@**************** Voice 063 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_171
	.byte	255, 245, 120, 127

@**************** Voice 064 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_172
	.byte	255, 253, 0, 165

@**************** Voice 065 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_173
	.byte	255, 0, 255, 165

@**************** Voice 066 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 067 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_153
	.byte	255, 245, 140, 165

@**************** Voice 068 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_174
	.byte	255, 0, 255, 165

@**************** Voice 069 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 070 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 071 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_175
	.byte	255, 240, 170, 165

@**************** Voice 072 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 073 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_031
	.word	map_029

@**************** Voice 074 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_179
	.byte	64, 247, 135, 127

@**************** Voice 075 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_180
	.byte	32, 0, 255, 165

@**************** Voice 076 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_181
	.byte	100, 0, 255, 165

@**************** Voice 077 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_182
	.byte	252, 0, 255, 165

@**************** Voice 078 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_183
	.byte	80, 240, 190, 180

@**************** Voice 079 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 080 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_184
	.byte	255, 0, 255, 127

@**************** Voice 081 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_185
	.byte	255, 0, 255, 127

@**************** Voice 082 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 083 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 084 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 085 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 086 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 087 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 088 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 089 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 090 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 091 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 092 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 093 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 094 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 095 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 096 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 097 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 098 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 099 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 100 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_153
	.byte	255, 0, 170, 0

@**************** Voice 101 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 0, 15, 0

@**************** Voice 102 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 103 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 104 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 105 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_032
	.word	map_030

@**************** Voice 106 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 107 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 108 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 109 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 110 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 111 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 112 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 113 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 114 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 115 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 116 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 117 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 118 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 119 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 120 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 121 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 122 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 123 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 124 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 125 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 126 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 127 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0



	.end
